# Generated by Django 3.1.5 on 2021-01-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gro', '0002_remove_list_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='list1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(blank=True, max_length=255)),
                ('quant', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='list',
        ),
    ]
